<template>
  <main>
    <section id="home" class="hero">
      <div class="hero-grid" aria-hidden="true"></div>
      <div class="hero-topline"><span>DESENVOLVEDOR DE SOFTWARE E ESTUDANTE DE CIÊNCIA DA COMPUTAÇÃO</span><span>ENGENHARIA / INTELIGÊNCIA / AUTOMAÇÃO</span></div>
      <div class="hero-copy"><p class="eyebrow hero-reveal">Olá, sou o Everton.</p><h1 class="hero-reveal">Marussi<span class="blue">.</span></h1><p class="hero-description hero-reveal">Da primeira linha de código<br>a sistemas que <em>conectam tudo.</em></p><div class="hero-actions hero-reveal"><a class="button light" href="#work">Conheça meus projetos <span>↗</span></a><a class="text-link" href="#about">Sobre mim ↓</a></div></div>
      <div class="portrait-panel hero-reveal"><div class="portrait-orbit" aria-hidden="true"></div><img v-if="portfolio.portrait" :src="portfolio.portrait" fetchpriority="high" width="500" height="500" alt="Everton Marussi Dias" class="portrait"><div v-else class="portrait-placeholder"><span class="portrait-monogram" aria-hidden="true">EM</span><span class="photo-label">ESPAÇO PARA RETRATO<br>Everton Marussi Dias</span></div><div class="portrait-caption"><span>DESENVOLVIMENTO COMPLETO.<br>VISÃO DO TODO.</span><span class="caption-cross">+</span></div></div>
      <div class="hero-bottom"><span>01 / UMA BREVE APRESENTAÇÃO</span><p>Arquitetura de software. Dispositivos conectados. IA aplicada.</p><a href="#welcome" aria-label="Ir para a apresentação">↓</a></div>
    </section>

    <section id="welcome" class="welcome"><div class="welcome-inner"><span class="eyebrow">TODO SISTEMA COMEÇA COM UMA IDEIA.</span><div class="welcome-stage"><h2 class="welcome-first">Boas-vindas<span>...</span></h2><p class="welcome-second">Ao meu<br><em>portfólio.</em></p></div><span class="welcome-foot">ROLE PARA CONHECER AS IDEIAS POR TRÁS DO CÓDIGO ↓</span></div></section>

    <section id="about" class="section about"><div class="section-label"><span>01 — SOBRE MIM</span><span>A PESSOA POR TRÁS DOS SISTEMAS</span></div><div class="about-grid"><h2 class="reveal">Eu conecto<br>os <em>pontos.</em></h2><div class="about-text reveal"><p class="large-copy">Sou Everton Marussi Dias. Desenvolvedor de software com formação em automação e cursando ciência da computação e uma curiosidade que vai além da tela.</p><p>Atuo em todo o ciclo de desenvolvimento de software: requisitos, regras de negócio, modelagem de dados, arquitetura, desenvolvimento full stack, infraestrutura e operação em produção.</p><p>A Automação Industrial me ensinou a conectar software ao mundo físico. A Ciência da Computação amplia essa base com matemática, algoritmos e Inteligência Artificial.</p><div class="about-facts"><div><span>ATUALMENTE</span><strong>Desenvolvedor de Software</strong><small>HION Soluções e Tecnologia</small></div><div><span>PRÓXIMO CAPÍTULO</span><strong>Ciência da Computação</strong><small>Graduação em fase de conclusão</small></div></div></div></div></section>

    <section id="journey" class="section journey"><div class="section-label"><span>02 — TRAJETÓRIA</span><span>CONSTRUÍDA UMA ETAPA POR VEZ</span></div><h2 class="reveal">Uma base sólida.<br><em>Sempre em evolução.</em></h2><div class="timeline"><article class="timeline-row reveal"><span class="timeline-date">FORMAÇÃO TÉCNICA</span><div><h3>Onde o código encontra o hardware.</h3><h4>ETEC Júlio de Mesquita · Automação Industrial</h4><p>Concluí o Ensino Médio integrado ao curso Técnico em Automação Industrial. Desenvolvi experiência prática em eletrônica, programação embarcada, automação e integração de software com dispositivos inteligentes.</p></div><span class="timeline-number">01</span></article><article class="timeline-row reveal"><span class="timeline-date">2023</span><div><h3>Uma ideia que conquistou reconhecimento.</h3><h4>Tomada Inteligente · Trabalho de Conclusão de Curso</h4><p>Desenvolvi a “Tomada Inteligente”, um protótipo para telemetria de energia elétrica residencial. O projeto foi apresentado na Semana Municipal de Ciência e Tecnologia de Santo André e conquistou o segundo lugar.</p></div><span class="timeline-number">02</span></article><article class="timeline-row reveal"><span class="timeline-date">JUL 2024 — ATUALMENTE</span><div><h3>Desenvolvendo para o mundo real.</h3><h4>HION · Programador de Sistemas da Informação</h4><p>Desenvolvo, mantenho e evoluo sistemas corporativos e industriais, dos requisitos à implantação. Construo serviços em Node.js e interfaces em Vue.js e React, integro APIs HTTP e gRPC, modelo bancos de dados e opero microsserviços em contêineres.</p><p>Atuo em aplicações ERP e IoT para web, computadores e dispositivos móveis, com gestão de usuários, monitoramento operacional e métricas de sistemas. Aplico análise de dados e redes LSTM à previsão da vida útil de baterias industriais.</p></div><span class="timeline-number">03</span></article><article class="timeline-row reveal"><span class="timeline-date">EM ANDAMENTO</span><div><h3>Aprofundando os fundamentos.</h3><h4>Ciência da Computação · Ênfase em Desenvolvimento de Software</h4><p>Estou em fase de conclusão da graduação, aprofundando minha base em matemática, estruturas de dados e algoritmos para IA. Exploro métodos numéricos, álgebra linear, otimização, CNNs e LSTMs em conjunto com a prática em engenharia de software.</p></div><span class="timeline-number">04</span></article></div></section>

    <section class="award section"><div class="award-number reveal">2<span>º</span><small>LUGAR / 2023</small></div><div class="award-copy reveal"><span class="eyebrow">UMA IDEIA. UM PROTÓTIPO. UMA CONQUISTA.</span><h2>Pequeno dispositivo.<br>Grande <em>reconhecimento.</em></h2><p>A Tomada Inteligente levou a telemetria de energia residencial à Semana Municipal de Ciência e Tecnologia de Santo André.</p><p class="award-note">Reconhecimento institucional e apoio envolvendo</p><div class="institutions"><span>SEBRAE</span><span>UFABC</span><span>Parque Tecnológico de<br>Santo André</span></div></div></section>

    <section id="work" class="section work"><div class="section-label"><span>03 — PROJETOS E APLICAÇÕES</span><span>IDEIAS QUE SE TORNAM SISTEMAS</span></div><div class="section-heading"><h2 class="reveal">Desafios diferentes.<br><em>Um olhar de engenharia.</em></h2><p>Projetos acadêmicos e experiência profissional em software, inteligência e dispositivos conectados.</p></div><article v-for="project in portfolio.projects" :key="project.id" class="project reveal"><div class="project-visual" :class="[project.visual, { 'project-gallery': project.id === '01' }]"><template v-if="project.id === '01'"><figure v-for="photo in portfolio.outletPhotos" :key="photo.src"><img :src="photo.src" :alt="photo.alt" loading="lazy" width="1600" :height="photo.src === portfolio.outletPhotos[0].src ? 1067 : 902"><figcaption>{{ photo.caption }}</figcaption></figure></template><img v-else-if="project.image" :src="project.image" :alt="project.imageLabel" loading="lazy"><template v-else><span class="project-visual-label">{{ project.category }}</span><span class="project-glyph" aria-hidden="true">{{ project.id === '01' ? '↯' : project.id === '02' ? 'ƒ(t)' : '{ }' }}</span><span class="image-slot">{{ project.imageLabel }}<br><small>Espaço reservado para imagem</small></span></template></div><div class="project-copy"><span class="eyebrow">{{ project.id }} / {{ project.category }}</span><h3>{{ project.title }}</h3><h4>{{ project.subtitle }}</h4><p>{{ project.description }}</p><div class="tags"><span v-for="tag in project.tags" :key="tag">{{ tag }}</span></div><details><summary>Conheça o contexto <span>+</span></summary><p>{{ project.detail }}</p></details></div></article></section>

    <section id="community" class="section community">
      <div class="section-label"><span>04 — COMUNIDADE E MENTORIA</span><span>TECNOLOGIA SE CONSTRÓI EM CONJUNTO</span></div>
      <div class="community-heading reveal"><span class="role-badge">ORGANIZADOR E MENTOR DE HACKATHONS</span><h2>Criando oportunidades.<br><em>Construindo futuros.</em></h2><p class="large-copy">Aproximando os alunos do mundo da tecnologia e das carreiras que podem construir nele.</p></div>
      <figure class="community-photo reveal"><img :src="portfolio.hackathon" alt="Hackathon WECTI na Universidade Cidade de São Paulo, com organizadores e participantes reunidos em uma sala de aula" width="1600" height="900" loading="lazy"><figcaption>Universidade Cidade de São Paulo (UNICID) · Hackathons e imersão em tecnologia</figcaption></figure>
      <div class="community-content"><div class="reveal"><span class="eyebrow">UNIVERSIDADE CIDADE DE SÃO PAULO</span><h3>Da sala de aula<br>aos desafios do mercado.</h3><p>Organizo hackathons universitários e atuo como mentor, criando experiências de imersão em tecnologia que conectam os alunos ao mercado de trabalho. Esses eventos reúnem aprendizado, colaboração e resolução de problemas na prática.</p></div><div class="community-roles reveal"><article><span>01 / ORGANIZADOR</span><h3>Fazendo a experiência acontecer.</h3><p>Participo da organização de hackathons na UNICID, reunindo alunos para explorar a tecnologia e suas aplicações no mercado de trabalho.</p></article><article><span>02 / MENTOR</span><h3>Apoiando a próxima geração.</h3><p>Como mentor, oriento os alunos em seus desafios técnicos, compartilho experiência prática e ajudo a transformar ideias em soluções.</p></article></div></div>
    </section>

    <section id="stack" class="section stack"><div class="section-label"><span>05 — TECNOLOGIAS</span><span>AS FERRAMENTAS ACOMPANHAM O DESAFIO</span></div><div class="section-heading"><h2 class="reveal">Construção com propósito.<br><em>Baseada em fundamentos.</em></h2><p>De um dispositivo a um sistema distribuído, escolho as ferramentas adequadas para cada camada.</p></div><div class="stack-grid"><article v-for="(group, index) in portfolio.stack" :key="group.name" class="stack-group reveal"><span class="stack-index">0{{ index + 1 }} /</span><h3>{{ group.name }}</h3><p>{{ group.note }}</p><ul><li v-for="item in group.items" :key="item"><span v-if="portfolio.icons[item]" class="tech-icon"><img :src="asset('icons/' + portfolio.icons[item] + '.svg')" alt="" width="28" height="28" loading="lazy"></span><span v-else class="tech-marker" aria-hidden="true">/</span>{{ item }}</li></ul></article></div><div class="principles"><span>ARQUITETURA</span><span>CONFIABILIDADE</span><span>INTEGRAÇÃO</span><span>CURIOSIDADE</span></div></section>

    <section id="contact" class="section contact"><div class="section-label"><span>06 — QUAL É O PRÓXIMO PASSO?</span><span>VAMOS CONVERSAR</span></div><div class="contact-grid"><div class="reveal"><h2>Boas ideias<br>começam com<br><em>um “olá”.</em></h2><p>Tem um projeto em mente, um desafio técnico ou uma ideia para compartilhar? Vou gostar de conhecer.</p><div class="social-links"><a v-if="portfolio.email" class="contact-channel email-channel" :href="'mailto:' + portfolio.email"><span class="channel-icon"><img :src="asset('icons/envelope.svg')" alt="" width="24" height="24"></span><span><strong>Enviar e-mail</strong><small>{{ portfolio.email }}</small></span><span class="channel-arrow" aria-hidden="true">↗</span></a><a v-if="portfolio.whatsapp" class="contact-channel whatsapp-channel" :href="whatsappUrl" target="_blank" rel="noopener noreferrer" aria-label="Chamar no WhatsApp (abre em uma nova aba)"><span class="channel-icon"><img :src="asset('icons/whatsapp.svg')" alt="" width="24" height="24"></span><span><strong>Chamar no WhatsApp</strong><small>{{ portfolio.whatsapp.display }}</small></span><span class="channel-arrow" aria-hidden="true">↗</span></a><a v-if="portfolio.github" :href="portfolio.github" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a v-if="portfolio.linkedin" :href="portfolio.linkedin" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div></div><form class="contact-form reveal" @submit.prevent="contact"><label for="name">01 / Seu nome</label><input id="name" v-model.trim="form.name" name="name" autocomplete="name" placeholder="Como posso chamar você?" maxlength="120" required><label for="email">02 / Seu e-mail</label><input id="email" v-model.trim="form.email" name="email" type="email" autocomplete="email" placeholder="voce@exemplo.com" maxlength="254" required><label for="message">03 / Sua mensagem</label><textarea id="message" v-model.trim="form.message" name="message" placeholder="Conte um pouco sobre sua ideia..." rows="4" maxlength="5000" required></textarea><p v-if="!portfolio.email" class="form-note">O contato direto está sendo configurado. Você pode copiar sua mensagem abaixo.</p><p v-else class="form-note">Seu aplicativo de e-mail será aberto com a mensagem pronta para enviar.</p><button class="button light" type="submit">{{ portfolio.email ? 'Abrir rascunho de e-mail' : 'Copiar mensagem' }} <span>↗</span></button><p class="form-status" role="status">{{ formStatus }}</p></form></div></section>
  </main>
</template>
<script>
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import portfolio from '../data/portfolio'
gsap.registerPlugin(ScrollTrigger)
export default {
  name: 'PortfolioHome',
  data: () => ({ portfolio, form: { name: '', email: '', message: '' }, formStatus: '' }),
  computed: {
    whatsappUrl() {
      return this.portfolio.whatsapp ? `https://wa.me/${this.portfolio.whatsapp.number}?text=${encodeURIComponent(this.portfolio.whatsapp.message)}` : ''
    }
  },
  mounted() {
    this.motion = gsap.matchMedia()
    this.motion.add('(prefers-reduced-motion: no-preference)', () => {
      gsap.from('.hero-reveal', { y: 36, opacity: 0, duration: 1.15, stagger: 0.13, ease: 'power3.out', clearProps: 'all' })
      gsap.utils.toArray('.reveal').forEach(el => gsap.from(el, { y: 35, opacity: 0, duration: 0.85, ease: 'power2.out', scrollTrigger: { trigger: el, start: 'top 92%', once: true }, clearProps: 'all' }))
      const tl = gsap.timeline({ scrollTrigger: { trigger: '.welcome', start: 'top top', end: '+=150%', scrub: 0.8, pin: true, anticipatePin: 1 } })
      tl.to('.welcome', { backgroundColor: '#1439dd', duration: 1 }, 0).to('.welcome-first', { opacity: 0, y: -70, scale: 0.88, duration: 1 }, 0.5).fromTo('.welcome-second', { opacity: 0, y: 80 }, { opacity: 1, y: 0, duration: 1 }, 1.1).to('.welcome', { backgroundColor: '#070a12', duration: 1 }, 2.3)
      gsap.to('.portrait-orbit', { rotation: 120, ease: 'none', scrollTrigger: { trigger: '.hero', start: 'top top', end: 'bottom top', scrub: 1 } })
    })
  },
  beforeDestroy() { if (this.motion) this.motion.revert() },
  methods: {
    asset(path) { return process.env.BASE_URL + path.replace(/^\//, '') },
    async contact() {
      if (!this.form.name || !this.form.message) { this.formStatus = 'Preencha seu nome e uma mensagem.'; return }
      const message = `Nome: ${this.form.name}\nE-mail: ${this.form.email}\n\n${this.form.message}`
      if (this.portfolio.email) {
        window.location.href = `mailto:${this.portfolio.email}?subject=${encodeURIComponent('Contato pelo portfólio de ' + this.form.name)}&body=${encodeURIComponent(message)}`
        this.formStatus = 'Seu rascunho está pronto. Envie a mensagem pelo seu aplicativo de e-mail.'
      } else {
        try { await navigator.clipboard.writeText(message); this.formStatus = 'Mensagem copiada. Nada foi enviado.' }
        catch (_) { this.formStatus = 'Não foi possível copiar neste navegador. Selecione e copie sua mensagem manualmente. Nada foi enviado.' }
      }
    }
  }
}
</script>
<style src="../assets/portfolio.css"></style>
